version: '{build}'

clone_depth: 5

environment:
  matrix:
  - PYTHON_VERSION: 3.6
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda36-x64

init:
- cmd: ''

install:
  # Add Miniconda to the PATH
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Setup always yes
  - conda config --set always_yes yes --set changeps1 no

  # Quietly update if needed
  # - conda update -q conda

  # Display conda version
  - conda info -a

  # Take the enviroment.yml but replace tensorflow-gpu with tensorflow,
  # we don't have GPUs on appveyor nodes and this will make
  # building the enviroment faster.
  - ps: (Get-Content -path .\environment.yml -Raw) -replace 'tensorflow-gpu','tensorflow' | Set-Content -Path environment_appveyor.yml

  # Create/update the sleap environment in case some dependencies changed.
  - conda env create -n sleap_appveyor -f environment_appveyor.yml

  # Activate things
  - activate sleap_appveyor

  # Conda Explicit Spec files don't include pip installed stuff.
  # See: https://github.com/conda/conda/issues/8372
  # We need to install this separately, what a mess.
  # - pip install PySide2 opencv-python imgaug cattrs

# Install dev requirements too.
  - pip install -r dev_requirements.txt

build: off
test_script:
  - cmd: activate sleap_appveyor
  - cmd: where python
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: python -m pytest tests/

