version: '{build}'

clone_depth: 5

environment:
  access_token:
    secure: T7XuBtHDu85Tk/d1AeyfhW3CVyzaoddTWmR4xsPIdQ3di0R6x8ncWqw3KrYXkWJm

  matrix:
  - PYTHON_VERSION: 3.6
    PYTHON_ARCH: "64"
    MINICONDA: C:\Miniconda36-x64

init:
- cmd: ''

install:
  # Add Miniconda to the PATH
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Setup always yes
  - conda config --set always_yes yes --set changeps1 no

  # Quietly update if needed
  # - conda update -q conda

  # Display conda version
  - conda info -a

  # Take the enviroment.yml but replace tensorflow-gpu with tensorflow,
  # we don't have GPUs on appveyor nodes and this will make
  # building the enviroment faster.
  - ps: (Get-Content -path .\environment.yml -Raw) -replace 'tensorflow-gpu','tensorflow' | Set-Content -Path environment_appveyor.yml

  # Create/update the sleap environment in case some dependencies changed.
  - conda env create -n sleap_appveyor -f environment_appveyor.yml

  # Activate things
  - activate sleap_appveyor

  # Conda Explicit Spec files don't include pip installed stuff.
  # See: https://github.com/conda/conda/issues/8372
  # We need to install this separately, what a mess.
  # - pip install PySide2 opencv-python imgaug cattrs

# Install dev requirements too.
  - pip install -r dev_requirements.txt

build: off
test_script:
  - cmd: activate sleap_appveyor
  - cmd: where python
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: python -m pytest tests/


# here we are going to override common configuration
for:

# override settings for `master` branch
-
  branches:
    only:
      - master

  # Build and deploy our documentation. This involves checking out
  # the repo, switching to the github pages branch, building the docs
  # from to gh-pages branch and pushing. See:
  # https://daler.github.io/sphinxdoc-test/includeme.html
  # for details on how to set this up.
  deploy_script:
    - cmd: git config --global credential.helper store
    - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - cmd: git config --global user.email "davidt0x@gmail.com"
    - cmd: git config --global user.name "David Turner"
    - cmd: activate sleap_appveyor
    - cmd: cd ..\
    - cmd: mkdir sleap-docs
    - cmd: cd sleap-docs
    - cmd: git clone https://github.com/murthylab/sleap.git html
    - cmd: cd html
    - cmd: git checkout -b gh-pages remotes/origin/gh-pages
    - cmd: cd ..\..\sleap\docs
    - cmd: make html push
