name: sleap

dependencies:
- python=3.6
- jsonpickle
- networkx
- tensorflow-gpu
- keras
- h5py
- pandas
- qtpy
- matplotlib
- scikit-image
- Shapely
- pip
- pip:
    - opencv-python
    - PySide2==5.12.0
    - imgaug
