name: sleap

dependencies:
- python=3.6
- attrs
- jsonpickle=1.2
- networkx
- tensorflow-gpu=2.1
- tensorboard=2.1
- scikit-learn
- h5py
- pandas
- Pillow
- Shapely
- psutil
- pyzmq
- pyyaml
- python-rapidjson
- pip
- pip:
    - opencv-python-headless==3.4.1.15
    - PySide2>=5.12.0,<=5.14.1
    - imgaug==0.3.0
    - cattrs==1.0.0rc0
    - qimage2ndarray==1.8
    - imgstore
    - jsmin
    - seaborn
    - scikit-video
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"