name: sleap

dependencies:
- python=3.6
- Pillow
- Shapely
- sleap::tensorflow=2.3.1
- sleap::pyside2=5.14.1
- conda-build=3.17
- anaconda-client
- conda-verify
- pip
- pip:
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"