name: sleap

dependencies:
- python=3.6
- attrs
- jsonpickle
- networkx
- tensorflow-gpu
- keras
- scikit-learn
- h5py
- pandas
- Shapely
- psutil
- pyzmq
- pip
- pip:
    - opencv-python==3.4.2.17
    - PySide2==5.12.0
    - imgaug
    - cattrs==1.0.0rc0
    - qimage2ndarray==1.8
    - imgstore