name: sleap

dependencies:
- python=3.6
- attrs
- jsonpickle
- networkx
- tensorflow-gpu
- keras
- scikit-learn
- h5py
- pandas
- Shapely
- pip
- pip:
    - opencv-python
    - PySide2==5.12.0
    - imgaug
    - cattrs==1.0.0rc0
    - qimage2ndarray==1.8
