name: sleap

dependencies:
- python=3.6
- attrs
- jsonpickle=1.2
- networkx
- cudatoolkit=10.1.*
- cudnn
- scikit-learn
- h5py
- pandas
- Pillow
- Shapely
- psutil
- pyzmq
- pyyaml
- python-rapidjson
- pip
- pip:
    - tensorflow==2.1
    - opencv-python-headless==3.4.1.15
    - PySide2==5.12.0
    - imgaug==0.3.0
    - cattrs==1.0.0rc0
    - qimage2ndarray==1.8
    - imgstore
    - jsmin
    - "--editable=./"
    - "--requirement=./dev_requirements.txt"