name: sleap

dependencies:
- python=3.6
- attrs
- jsonpickle=1.1
- networkx
- cudatoolkit=10.0.*
- cudnn
- scikit-learn
- h5py
- pandas
- Shapely
- psutil
- pyzmq
- pyyaml
- python-rapidjson
- pip
- pip:
    - opencv-python-headless==3.4.1.15
    - PySide2==5.12.0
    - imgaug
    - cattrs==1.0.0rc0
    - qimage2ndarray==1.8
    - imgstore
    - tensorflow-gpu==2.0