"new": QKeySequence.New
"open": QKeySequence.Open
"save": QKeySequence.Save
"save as": QKeySequence.SaveAs
"close": QKeySequence.Close
"add videos": Qt.CTRL + Qt.Key_A
"next video": QKeySequence.Forward
"prev video": QKeySequence.Back
"mark frame": Qt.CTRL + Qt.Key_M
"goto marked": Qt.CTRL + Qt.SHIFT + Qt.Key_M
"extract clip": Qt.CTRL + Qt.Key_E
"add instance": Qt.CTRL + Qt.Key_I
"delete instance": Qt.CTRL + Qt.Key_Backspace
"transpose": Qt.CTRL + Qt.Key_T
"select next": QKeySequence(Qt.Key.Key_QuoteLeft)
"clear selection": QKeySequence(Qt.Key.Key_Escape)
"goto next":
"goto prev":
"goto next suggestion": QKeySequence.FindNext
"goto prev suggestion": QKeySequence.FindPrevious
"goto next track":
"show labels": Qt.CTRL + Qt.Key_Tab
"show edges": Qt.CTRL + Qt.SHIFT + Qt.Key_Tab
"show trails": 
"color predicted": 
"fit": Qt.CTRL + Qt.Key_Equal