main:

- name: method
  label: Method
  type: stacked
  default: random
  options: random,strides,pca,brisk,proofreading
  #removing hog for now since it's not implemented correctly

  strides:
  - name: per_video
    label: Suggestions per video
    type: int
    default: 10
    range: 1,1000
  random:
  - name: per_video
    label: Suggestions per video
    type: int
    default: 10
    range: 1,1000
  pca:
  - name: clusters
    label: Number of clusters
    type: int
    default: 5
  - name: per_cluster
    label: Samples per cluster
    type: int
    default: 5
  - name: initial_samples
    label: Samples before clustering
    type: int
    default: 200
    range: 10,1000
  - name: pca_components
    label: Number of PCA components
    type: int
    default: 5
  hog:
  - name: clusters
    label: Number of clusters
    type: int
    default: 5
  - name: per_cluster
    label: Samples per cluster
    type: int
    default: 5
  - name: sample_step
    label: Frame sampling step size
    type: int
    default: 5
  - name: pca_components
    label: Number of PCA components
    type: int
    default: 5
  brisk:
  - name: clusters
    label: Number of clusters
    type: int
    default: 5
  - name: per_cluster
    label: Samples per cluster
    type: int
    default: 5
  - name: initial_samples
    label: Samples before clustering
    type: int
    default: 200
    range: 10,1000
  - name: pca_components
    label: Number of PCA components
    type: int
    default: 5
  proofreading:
  - name: score_limit
    label: Low score (lt)
    type: float
    default: 3.0
    range: 0,100
  - name: instance_limit
    label: Instance count (gte)
    type: int
    default: 2
    range: 1,10

- name: generate_button
  label: Generate Suggestions
  type: button
  default: main action