model:

- name: output_type
  label: Training For
  type: list
  options: confmaps,topdown,pafs,centroids
  default: confmaps

- name: arch # backbone_name
  label: Architecture
  type: list
  default: 
  options: LeapCNN,UNet,StackedUNet,StackedHourglass,ResNet50,DenseNet121,DenseNet169,DenseNet201,GeneralizedDenseNet,UDenseNet,MobileNetV1,MobileNetV2,NASNetMobile,NASNetLarge,GeneralizedNASNet,HigherHRNet

- name: pretrained
  label: Pretrained
  type: bool
  default: False

- name: down_blocks
  label: Down Blocks
  type: int
  default: 0

- name: up_blocks
  label: Up Blocks
  type: int
  default: 0

- name: convs_per_depth
  label: Convolutions per depth
  type: int
  default: 0

- name: num_filters
  label: Filters
  type: int
  default: 0

- name: kernel_size
  label: Kernel Size
  type: int
  default: 0
  
- name: upsampling_layers
  label: Upsampling Layers
  type: bool
  default: False

- name: interp
  label: Interpolation
  type: list
  default: bilinear
  options: bilinear

# stacked model:
- name: num_stacks
  label: Stacks
  type: int
  default: 3

# - name: batch_norm
#   label: Batch norm
#   type: bool
#   default: True

# - name: intermediate_inputs
#   label: Intermediate inputs
#   type: bool
#   default: True

# - name: initial_stride
#   label: Initial stride
#   type: int
#   default: 1

# skeletons?

datagen:

- name: scale
  label: Scale (rescale factor)
  type: double
  default: 0

- name: sigma
  label: Sigma (for datagen)
  type: double
  default: 0

- name: instance_crop
  label: Crop images to instances
  type: bool
  default: False

- name: min_crop_size
  label: Minimum crop size
  type: list
  dtype: int
  options: 0,64,128,256,512
  default: 0

#- name: negative_samples
#  label: Negative samples (if cropping)
#  type: int
#  default: 0

- name: augment_rotation
  label: Augmentation rotation
  type: int
  default: 0
  range: 0,360

- name: augment_scale_min
  label: Augmentation scale (min)
  type: double
  default: 0.0

- name: augment_scale_max
  label: Augmentation scale (max)
  type: double
  default: 0.0

trainer:

- name: val_size
  label: Validation Size
  type: double
  default: 0.0

- name: optimizer
  label: Optimizer
  type: list
  default: adam
  options: adam,rmsprop

- name: amsgrad
  label: AMSGrad (for adam)
  type: bool
  default: False

- name: learning_rate
  label: Learning Rate
  type: sci
  default: 0

- name: batch_size
  label: Batch Size
  type: int
  default: 0

- name: num_epochs
  label: Epochs
  type: int
  default: 0
  range: 0,1000

- name: steps_per_epoch
  label: Steps (batches) per Epoch
  type: int
  default: 0
  range: 0,1000

- name: shuffle_initially
  label: Shuffle Initially
  type: bool
  default: False

- name: shuffle_every_epoch
  label: Shuffle Every Epoch
  type: bool
  default: False

- name: reduce_lr_min_delta
  label: Reduce LR Min. Delta
  type: sci
  default: 0

- name: reduce_lr_factor
  label: Reduce LR Factor
  type: sci
  default: 0.0

- name: reduce_lr_patience
  label: Reduce LR Patience
  type: int
  default: 0

- name: reduce_lr_cooldown
  label: Reduce LR Cooldown
  type: int
  default: 0

- name: reduce_lr_min_lr
  label: Reduce LR Min. LR
  type: sci
  default: 0

- name: early_stopping_min_delta
  label: Early Stopping Min. Delta
  type: sci
  default: 0

- name: early_stopping_patience
  label: Early Stopping Patience
  type: sci
  default: 0

output:

- name: save_every_epoch
  label: Save Every Epoch
  type: bool
  default: False
  
- name: save_best_val
  label: Save Best Val
  type: bool
  default: False

- name: run_name
  label: Training Run Name
  type: string
  default:

- name: save_dir
  label: Output Directory
  type: file_dir
  default: 

- name: tensorboard_dir
  label: Tensorboard Directory
  type: file_dir
  default:

buttons:

- name: save_as
  label: Save Profile As...
  type: button
  default: main action

spacer:
