# Continuous integration using conda installation
name: CI

# Run on any push
# on: push
on:
  push:
    branches:
      # - develop
      - tf23

jobs:
  build:
    name: Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment_build.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment_build.yml', 'requirements.txt') }}
      - name: Setup Miniconda
        # https://github.com/conda-incubator/setup-miniconda
        uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          python-version: 3.6
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          environment-file: environment_build.yml
          activate-environment: sleap
      - name: Print environment info
        shell: bash -l {0}
        run: |
          which python
          conda info
      - name: Conda list
        if: matrix.os != 'windows-latest'
        shell: pwsh
        run: conda list
      - name: Test with pytest (Windows)
        if: matrix.os != 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          pytest
      - name: Test with pytest (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          sudo apt-get install xvfb libxkbcommon-x11-0
          sudo Xvfb :1 -screen 0 1024x768x24 </dev/null &
          export DISPLAY=":1"
          xvfb-run pytest --cov=sleap --cov-report=xml tests/
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest'