# This workflow tests the package with conda

name: Conda package tests

# Run on any push or pull request
on: [push, pull_request]

jobs:
  build:
    name: Conda package test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.6
          environment-file: environment_no_cuda.yml
          activate-environment: sleap
      - name: Print environment info
        shell: bash -l {0}
        run: |
          which python
          conda info
          conda list
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest tests
