# Builds static content for GitHub pages.

name: Build website

on:
  push:
    branches:
      # - master  # Branch that triggers updates
      - tf23  # Branch that triggers updates

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment_build.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment_build.yml', 'requirements.txt') }}
      - name: Setup Miniconda
        # https://github.com/conda-incubator/setup-miniconda
        uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          python-version: 3.6
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Build
        run: |
          pip install -r dev_requirements.txt
          cd docs
          python make_api_doctree.py
          sphinx build -m . build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages-test
          publish_dir: ./build